language: node_js
node_js:
  - "stable"
env:
  - CC_TEST_REPORTER_ID=781f3820426f33297e9e33a495b90bec290c3afc24431536650f2ef014dbf364
addons:
  code_climate:
      repo_token: 781f3820426f33297e9e33a495b90bec290c3afc24431536650f2ef014dbf364
cache:
  directories:
  - node_modules
before_script:
  - npm install codeclimate-test-reporter -g
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn coverage
  - yarn test
  - yarn build
after_success:
  - codeclimate-test-reporter < ./coverage/lcov.info
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
